export default {
	CART: {
		ADD: 'CART_ADD'
	},
	API: {
		PRODUCTS: {
			REQUEST: 'API_PRODUCTS_REQUEST',
			DONE: 'API_PRODUCTS_DONE'
		},
		CHECKOUT: {
			REQUEST: 'API_CHECKOUT_REQUEST',
			DONE: 'API_CHECKOUT_DONE'
		}
	}
};
